### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by technoicon** [dicarlosystems/manufacturer-invoiceninja#2]
Not sure why but i'm unable to install this.  Saying my server has a memory error.

Would have thought I would be able to install it?  Let me know if you need more info.

PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/sbin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/sbin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

**Comment by chrisdicarlo** [comment]
It looks like composer is running out of memory.  Try increasing the memory limit from the command-line:

`php -d memory_limit=-1 composer require dicarlosystems/manufacturer`

**Comment by chrisdicarlo** [comment]
Did that solve your issue?  If so, I'll close issue.

**Comment by technoicon** [comment]
That's fine close it.  I haven't tried the fix.

**Comment by chrisdicarlo** [comment]
Thanks!
