### ISSUE TITLE
Parse error: syntax error, unexpected 'use' (T_USE)

### ISSUE THREAD

**Issue by mikes-techzone** [dicarlosystems/manufacturer-invoiceninja#3]
Hello,

when I try to execute the command `php artisan module:migrate Manufacturer` I get the following error message 
`In 2018_09_04_223258_add_serialized_field.php line 6:

  Parse error: syntax error, unexpected 'use' (T_USE)`

can you help me?

Regards

**Comment by chrisdicarlo** [comment]
It looks like a quality check placeholder squeaked through.  Remove the following lines from the database migration and it should work:

// phpcs:disable
PSR1.Classes.ClassDeclaration.MissingNamespace

**Comment by mikes-techzone** [comment]
Thanks, that worked.
