### ISSUE TITLE
module crush when enter /expenses/create with HTTP ERROR 500

### ISSUE THREAD

**Issue by KrazyIvan-** [dicarlosystems/manufacturer-invoiceninja#4]

**Comment by chrisdicarlo** [comment]
Can you attach any log information related to the exception?

**Comment by KrazyIvan-** [comment]
HP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /www/html/ninja/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 718, referer: http://127.0.0.1:81/expenses/create

**Comment by KrazyIvan-** [comment]
[Wed Dec 18 03:34:08.070389 2019] [php7:error] [pid 17949] [client 127.0.0.1:39626] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /www/html/ninja/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 296, referer: http://127.0.0.1:81/expenses/create
[Wed Dec 18 03:34:08.072752 2019] [php7:error] [pid 17949] [client 127.0.0.1:39626] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 81920 bytes) in /www/html/ninja/vendor/composer/ClassLoader.php on line 444, referer: http://127.0.0.1:81/expenses/create
[Wed Dec 18 03:34:22.066578 2019] [php7:error] [pid 17950] [client 127.0.0.1:39628] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /www/html/ninja/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 296, referer: http://127.0.0.1:81/expenses/create
[Wed Dec 18 03:34:22.068933 2019] [php7:error] [pid 17950] [client 127.0.0.1:39628] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 81920 bytes) in /www/html/ninja/vendor/composer/ClassLoader.php on line 444, referer: http://127.0.0.1:81/expenses/create

**Comment by chrisdicarlo** [comment]
This looks to be failing in the core Laravel classes. You can try increasing your memory limit in your php.ini file.

**Comment by KrazyIvan-** [comment]
does not help 512M even -1 not help
just disable modules all work normal

**Comment by chrisdicarlo** [comment]
Can you try leaving the Manufacturer module enabled but disable the Expenses and Vendors module?

**Comment by KrazyIvan-** [comment]
btw. Manufacturer does not show on the menu

**Comment by KrazyIvan-** [comment]
Reports/Produces also crush,
[Wed Dec 18 04:09:55.133515 2019] [php7:error] [pid 20232] [client 127.0.0.1:40356] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /www/html/ninja/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 718, referer: http://127.0.0.1:81/settings/products
[Wed Dec 18 04:09:55.133674 2019] [php7:error] [pid 20232] [client 127.0.0.1:40356] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0, referer: http://127.0.0.1:81/settings/products

**Comment by chrisdicarlo** [comment]
The module itself does not show in the sidebar - it adds functionality to the products page, etc.

Can you provide the following info about your environment:
PHP version
Web server / environment (e.g. Valet / Homestead, Nginx, Apache)

**Comment by chrisdicarlo** [comment]
> does not help 512M even -1 not help
> just disable modules all work normal

And if you leave all the standard modules enabled the error disappears?

**Comment by KrazyIvan-** [comment]
PHP 7.2.24-0 +mysql + ubuntu .18.04.1 + Apache
16G RAM, 8 CPU
disabled module from settings work all normal, enabled crash start.

I try on clean DB, same crashing.

**Comment by KrazyIvan-** [comment]
![image](https://user-images.githubusercontent.com/10627542/71058300-54d2c200-219a-11ea-8c4d-09a5a52ba4eb.png)
nothing changes in the Product page. Enable or disable page look same

**Comment by chrisdicarlo** [comment]
Just to confirm, you ran the installation and the migrations as described in the README?
I can't reproduce the issue locally :confused:

I'm spinning up a new pristine environment to mimic your environment more closely.  Do you have any other custom modules installed?

**Comment by chrisdicarlo** [comment]
Did you clone the develop branch for the Invoice Ninja installation or did you use the downloadable zip file?  The module depends on the develop branch - the download is based off the master branch.

**Comment by KrazyIvan-** [comment]
Steps are as follow:
1)
cd /var/www/html
git clone https://github.com/invoiceninja/invoiceninja.git
cd /var/www/html/invoiceninja
composer install
sudo chown -R www-data:www-data /var/www/html/invoiceninja/
sudo chmod -R 775 /var/www/html/invoiceninja/

2)  Apache is point /var/www/html/invoiceninja as root
	open browser http://127.0.0.1
set sql:
CREATE SCHEMA `ninja` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'ninja'@'localhost' IDENTIFIED BY 'ninja';
GRANT ALL PRIVILEGES ON `ninja`.* TO 'ninja'@'localhost';
FLUSH PRIVILEGES;
	setup account 
	all done (do not logon yet), go step 3)
3)
sudo chmod 777 storage/logs/laravel-error.log
php artisan module:install dicarlosystems/manufacturer --type=github-https
php artisan module:migrate Manufacturer

4) open browser http:/// now login.

5) open REPORT crash... and soon

**Comment by chrisdicarlo** [comment]
So the initial clone would have defaulted to using the master branch.  Can you try checking out the develop branch:

``
git checkout -b develop
``

**Comment by KrazyIvan-** [comment]
yes, now work with develop branch 
thank you very much

**Comment by chrisdicarlo** [comment]
No problem!
